### ISSUE TITLE
Emacs for python development on remote servers

### ISSUE THREAD

**Issue by hek14** [jixiuf/vterm-toggle#1]
谢谢你解决了我在远程编辑文件时的一个痛点!
不过我还有两个小问题想请教一下您:
1. python development:
我现在用的是elpy来提供一些IDE features. 但是我在tramp编辑远程文件时, elpy的rpc进程无法识别远程环境(elpy作者已经表示无法提供这个feature). 您有什么解决方案吗? anaconda-mode我也试过, 同样无法让server跑在远程服务器上.
2. better terminal in emacs:
vterm 目前感觉比emacs term/ansi-term要好一些, 但是还是有一些terminal中的feature 无法模拟:
我在iterm2中使用了fzf来模糊搜索, 但是在vterm buffer中, 使用fzf 出来的candidate 画面没法看.

**Comment by jixiuf** [comment]
1 我无能为力， 
2 的问题能否给我截图看看，看看是不是跟这个问题有关，https://github.com/akermu/emacs-libvterm/pull/72
