### ISSUE TITLE
Support multiple hopes

### ISSUE THREAD

**Issue by OlivierCazade** [jixiuf/vterm-toggle#14]
Hello,

Thank you for the work done on this project.

A one additional feature could be to support multiple hope.

When editing file with ssh and sudo combined like this : 

`/ssh:user@host|sudo:root@host:/home/user/file`

vterm-toggle-cd only try to run the sudo command and doesn't make the ssh command : 

```
$ sudo -u root -s -H -p P""a""s""s""w""o""r""d"":
Password:
Sorry, try again.
Password:
````

**Comment by opsnull** [comment]
same issue，please support multiple hopes。

**Comment by jixiuf** [comment]
vterm support tramp now
