### ISSUE TITLE
exit term is not killing the window

### ISSUE THREAD

**Issue by Ergus** [jixiuf/vterm-toggle#18]
Hi:

When in a toggled vterm if I insert exit the terminal finishes, but the window is not killed (like in multi-term for example).

I tried `vterm-toggle-reset-window-configration-after-exit` but is resets the configuration to the initial configuration when the vterm window was toggled on or created.

Is it possible to add an option to kill the window if I do an exit? OR add an special value for `vterm-toggle-reset-window-configration-after-exit`? something like `'kill-window-only` or so?

**Comment by jixiuf** [comment]
> Hi:
> 
> When in a toggled vterm if I insert exit the terminal finishes, but the window is not killed (like in multi-term for example).
> 
> I tried `vterm-toggle-reset-window-configration-after-exit` but is resets the configuration to the initial configuration when the vterm window was toggled on or created.
> 
> Is it possible to add an option to kill the window if I do an exit? OR add an special value for `vterm-toggle-reset-window-configration-after-exit`? something like `'kill-window-only` or so?

done.

**Comment by Ergus** [comment]
Thanks

**Comment by Ergus** [comment]
> 
> done.

BTW: 

Maybe it will be usefull to mention these options in the Readme. Specially for new users.
