### ISSUE TITLE
Issue with (vterm-toggle-scope 'projectile)

### ISSUE THREAD

**Issue by Ergus** [jixiuf/vterm-toggle#19]
Hi:

When I set this `(vterm-toggle-scope 'projectile)` option vterm-toggle and vterm-toggle-cd creates a new vterm buffer every time it is called if the current file is not in a project. Even if it is the same file. IMO the expected behavior if there is not project for the current file the behavior must be the same than when it is nil right? not create a new shell everytime... but check if there is one already for the current file/path.

Is this intended?

BTW: Maybe vterm-toggle should consider to use the internal project api if available instead of depending on external projectile?

**Comment by patrickt** [comment]
I’m still seeing this on version 20201130.617.

**Comment by patrickt** [comment]
Ah, never mind, sorry—what I had to do was change my config so that `vterm-toggle-scope` was `'project` instead of `'projectile`. Perhaps it should warn if `projectile` is provided instead of `project`.

**Comment by jixiuf** [comment]
done.
