### ISSUE TITLE
Evil state switching suggestions

### ISSUE THREAD

**Issue by noctuid** [jixiuf/vterm-toggle#2]
`vterm-toggle--switch-evil-state` should check whether evil mode is actually enabled not just if evil has been loaded (e.g. `(bound-and-true-p evil-local-mode)`). It would also be nice if there was a setting to disable this functionality (don't switch states when toggling).

Also, thanks for this package. `vterm-toggle-cd` is very convenient.

**Comment by jixiuf** [comment]
if you don't want to switch states when toggling:
```
(setq vterm-toggle-evil-state-when-enter nil)
(setq vterm-toggle-evil-state-when-leave nil)
```

**Comment by noctuid** [comment]
Awesome, thanks!
