### ISSUE TITLE
How to create a second vterm

### ISSUE THREAD

**Issue by halloleo** [jixiuf/vterm-toggle#22]
I use `vterm-toggle` to create a vterm window and then later to switch to it. This works great! :-)

However, how can I create an independent second vterm window - and then late switch to it?

**Comment by jixiuf** [comment]
C-u ‘vterm-toggle’

**Comment by halloleo** [comment]
Aha, cool! With this I can create a new vterm window "`vterm<2>`". 

But how can I specific how to switch to which of the two windows? I tried a few things (with and without C-u) but it is not clear to me.

**Comment by jixiuf** [comment]
it should switch to the recent used vterm buffer.
