### ISSUE TITLE
which-key buffer problem

### ISSUE THREAD

**Issue by injae** [jixiuf/vterm-toggle#3]
which-key buffer size is transformed by vterm-toggle.

![Screenshot-20190723140332-1920x1054](https://user-images.githubusercontent.com/16817498/61683982-b3625400-ad52-11e9-8681-8a13265df11d.png)
![Screenshot-20190723140405-1920x1054](https://user-images.githubusercontent.com/16817498/61683992-c07f4300-ad52-11e9-9a67-7c244536a07c.png)

**Comment by jixiuf** [comment]
try this 
```
(setq vterm-toggle-fullscreen-p nil)
(add-to-list 'display-buffer-alist
             '("^v?term.*"
                (display-buffer-reuse-window display-buffer-in-direction)
                (reusable-frames . visible)
                (direction . bottom)
                ;;(window-width . 0.3)
                (window-height . 0.3)))

```
which-key-mode and vterm  use the same side window when you use `display-buffer-in-side-window`

**Comment by injae** [comment]
Thank you for your reply.
vterm-toggle function error
symbol function definition is void: display-buffer-in-direction

**Comment by jixiuf** [comment]
try replace  `display-buffer-in-direction` with `display-buffer-at-bottom`

sorry 
`display-buffer-in-direction`  is added in emacs27
```
+++
** New buffer display action function 'display-buffer-in-direction'.
This function allows to specify the location of the window chosen by
'display-buffer' in various ways.


```

**Comment by injae** [comment]
The issue has been resolved.
Thank you for quick response.
