### ISSUE TITLE
vterm-toggle-show: Symbol’s value as variable is void: vterm-buffer-name

### ISSUE THREAD

**Issue by juhp** [jixiuf/vterm-toggle#31]
In a fresh started emacs I get this error with vterm-toggle-20210531.1453, when vterm is not running yet.
I haven't tried yet in a vanilla emacs session, but this looks like a bug to me, unless I am doing something wrong?

**Comment by jixiuf** [comment]
try upgrade vterm-toggle,  63723fcaf602cb6cc6e5a13d8c57ef7967a3653a  should fix this .

**Comment by juhp** [comment]
Looks good in vterm-toggle-20210629.927, thank you!
