### ISSUE TITLE
Symbol's value as variable is void: vterm-other-window

### ISSUE THREAD

**Issue by emillo** [jixiuf/vterm-toggle#32]
After today update whenever I try to call vterm-toggle I get the message `Symbol's value as variable is void: vterm-other-window` in the minibuffer

perhaps line 53 should read ```(defvar vterm-other-window "vterm")``` ?

**Comment by nylar** [comment]
Fixed for me with https://github.com/jixiuf/vterm-toggle/commit/2258eb19e8bde75f79505c4306f3476bcedce56c

**Comment by emillo** [comment]
Yes I confirm it's fixed for me too, thanks!
