### ISSUE TITLE
Unused lexical variables and/or functions

### ISSUE THREAD

**Issue by Nekosis** [jixiuf/vterm-toggle#42]
Greetings,

There appear to be a few unused lexical variables and/or functions in `vterm-toggle.el`.

Using the [Elpaca package manager](https://github.com/progfolio/elpaca) to byte-compile and thus install the package, I get this warning in the Elpaca Log:

```
vterm-toggle                   byte-compilation     vterm-toggle.el:229:56: Warning: Unused lexical variable `cur-port'              10.006751
```

@progfolio has showed me a few warnings they received during byte compilation (see https://github.com/progfolio/elpaca/issues/182#issuecomment-1714780360): 

```
vterm-toggle.el:211:2: Warning: docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...') 185.809374
vterm-toggle.el:229:47: Warning: Unused lexical variable ‘cur-user’              185.810434
vterm-toggle.el:229:56: Warning: Unused lexical variable ‘cur-port’              185.819951
vterm-toggle.el:395:15: Warning: the function ‘project-roots’ is not known to be defined. 185.839441
```

Would you please look into this?

Thank you in advance!

**Comment by jixiuf** [comment]
done.
