### ISSUE TITLE
Option for vterm-toggle-cd to always activate existing vterm buffer

### ISSUE THREAD

**Issue by noctuid** [jixiuf/vterm-toggle#6]
It would be nice if there was a different command or an option for `vterm-toggle-cd` that would activate a recent vterm buffer even if no prompt can be found (with `vterm-toggle-use-dedicated-buffer` still nil). So when the current buffer is not a vterm buffer, it would always activate a recent vterm buffer if there is one but would only insert `cd` if the prompt is available.

Sometimes it's nice to get a new terminal if I have something running in the old one, but I'd rather have another keybinding to use in that case.

**Comment by jixiuf** [comment]
try 
```
(setq vterm-toggle-cd-auto-create-buffer nil)
```

**Comment by noctuid** [comment]
Awesome, thank you!

**Comment by innerout** [comment]
Could you add this in the README ? It is pretty useful and probably will be essential for many people.

**Comment by jixiuf** [comment]
readme is updated .
forgive my poor English,
pull request are welcome to improve the readme or anything else.

**Comment by innerout** [comment]
I just made a suggestion, I did not mean to be aggressive. Your English are just fine don't worry!
