### ISSUE TITLE
vterm-toggle-cd improvements

### ISSUE THREAD

**Issue by Silex** [jixiuf/vterm-toggle#7]
Hello,

I discovered `vterm-toggle-cd` handles TRAMP! Nice work :+1: 

Here are a few use cases that are not handled correctly:

- Using another port (syntax `user@host#port`) translates to `ssh user@host:port` when it'd be `ssh -p port user@host`
- Using docker-tramp (https://github.com/emacs-pe/docker-tramp.el) but that's probably asking for too much :-)

**Comment by jixiuf** [comment]
1 should be fixed .

2  docker-tramp should be supported now .

**Comment by Silex** [comment]
Amazing! :+1: Will test & report.

**Comment by Silex** [comment]
I have invalid function `tramp-get-sh-extra-args` in Emacs 26.3. Seems to be a 27+ function only.

**Comment by jixiuf** [comment]
please try again .

**Comment by Silex** [comment]
Alright! It works but IMHO there's room for improvement:

* SSH
  * it yield `ssh -l USER -p PORT  -e none -t -t HOST /bin/sh`
  * more or less OK, except I have to type "bash" in order to get a "normal" shell, the one you'd expect if you manually ssh'ed to the box
* Docker
  * it yields `docker  exec -it -u USER CONTAINER sh`
  * this only works if you use `/docker:root@container`, in practice you do `/docker:container` and the user is nil, and thus `vterm-toggle-cd` fails.
  * same "bash" issue as with SSH, but less problematic because docker.

I think the minimal improvement should be to handle the user `nil` case in docker, but for the rest it's complicated, if you try & use bash people will want to use sh/zsh. Maybe there's something to be done with `shell-file-name` tho.

**Comment by jixiuf** [comment]
try again 
 
> Alright! It works but IMHO there's room for improvement:
> 
> * SSH
>   
>   * it yield `ssh -l USER -p PORT  -e none -t -t HOST /bin/sh`
>   * more or less OK, except I have to type "bash" in order to get a "normal" shell, the one you'd expect if you manually ssh'ed to the box

this should be fixed 
> * Docker
>   
>   * it yields `docker  exec -it -u USER CONTAINER sh`
>   * this only works if you use `/docker:root@container`, in practice you do `/docker:container` and the user is nil, and thus `vterm-toggle-cd` fails.
this should be fixed.
>   * same "bash" issue as with SSH, but less problematic because docker.

I decided not to fix this for docker 
you can 
```
(defun vterm-toggle-after-ssh-login (method user host port localdir)
  (when (string-equal "docker" method)
    (vterm-send-string "bash")
    (vterm-send-return)))

(add-hook 'vterm-toggle-after-remote-login-function 'vterm-toggle-after-ssh-login)
```

**Comment by Silex** [comment]
Perfect! Thanks for everything :+1:
