### ISSUE TITLE
Restart vterm in `vterm-toggle-cd` if vterm process has exited

### ISSUE THREAD

**Issue by failable** [jixiuf/vterm-toggle#9]
Currently `vterm-toggle-cd` will start vterm when the first time it is called. But if the process exited by `C-d` or `exit RET`, calling `vterm-toggle-cd` will only pop the vterm buffer, without restarting the process. I will this feature maybe helpful.

**Comment by jixiuf** [comment]
why not just 

```
(setq  vterm-kill-buffer-on-exit t)
```

**Comment by failable** [comment]
Didn't know this setting...Thanks for the tip!
